name: ci

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github Security Monitor
        uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - continue-on-error: true
        name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - id: meta
        name: Docker metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
      - if: github.event_name == 'pull_request'
        name: Build and push - pull-request
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: "."
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
      - if: github.ref == 'refs/heads/master'
        name: Build and push - master
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: "."
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.IMAGE_NAME }}:latest
      - if: github.ref == 'refs/tags/*'
        name: Build and push - tags
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: "."
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
      - continue-on-error: true
        if: github.event_name == 'pull_request'
        name: Docker Scout - compare
        uses: docker/scout-action@v1
        with:
          command: compare
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-unchanged: true
          image: ${{ steps.meta.outputs.tags }}
          only-severities: critical,high,medium
          to: ${{ env.IMAGE_NAME }}:latest
          write-comment: true
      - continue-on-error: true
        if: github.ref == 'refs/heads/master'
        name: Docker Scout - cves
        uses: docker/scout-action@v1
        with:
          command: cves
          ignore-unchanged: true
          image: ${{ steps.meta.outputs.tags }}
          only-fixed: true
          only-severities: medium,high,critical
          sarif-file: sarif.output.json
          summary: true
      - if: github.ref == 'refs/heads/master'
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: warn
          name: scout-results
          path: sarif.output.json
